#!/usr/bin/env python3
"""Build the merge-lane debug config FROM the tracked config.yaml plus only the GA-493 debug
overrides. A config passed as GRAPH_API_CONFIG REPLACES config.yaml, so the old
ga493_bbox_replay.yaml (a full copy taken before 2026-09-14) silently carried the legacy merge
engine and the old similarity weights; this generator keeps every merge/association/similarity
key exactly as the branch's config.yaml states them and prints the parsed difference.

    python3 lost3dsg/test/debug_configs/make_merge_debug_config.py [--engine legacy]
"""
import argparse
import copy
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
TRACKED = os.path.join(REPO, "lost3dsg", "src", "perception_module", "config.yaml")

OVERRIDES = {
    "simulation": False,
    "run": {"cap_min": 5, "gt_semantic": False, "rviz": False, "show": False, "overlay": False,
            "map_draw": False, "wall_detector": True, "pose_source": "simulator"},
    "perception": {"backend": "modal", "modal_endpoint": "", "cloud_timeout_s": 60.0,
                   "provider": "fal", "containment_threshold": 0.85, "fov_max_depth_m": 1.8,
                   "vlm_strikes_max": 3},
    "perception_parallel": {"enabled": True, "bbox_backend": "cuda", "bbox_cuda_devices": [0]},
    "archive": {"per_detection": False},
    "hooks": {"filter": ""},
    "vlm": {"timeout": 60.0, "crop_concurrency": 4, "crop_timeout": 15.0, "grid_cells": 0},
}


def merge(base, over):
    out = copy.deepcopy(base)
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = v
    return out


def flat(d, p=""):
    out = {}
    for k, v in d.items():
        if isinstance(v, dict):
            out.update(flat(v, p + k + "."))
        else:
            out[p + k] = v
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", choices=["evidence", "legacy"], default=None,
                    help="override association.merge_engine (default: as config.yaml)")
    ap.add_argument("--cap-min", type=int, default=5)
    a = ap.parse_args()
    base = yaml.safe_load(open(TRACKED))
    over = copy.deepcopy(OVERRIDES)
    over["run"]["cap_min"] = a.cap_min
    if a.engine:
        over["association"] = {"merge_engine": a.engine}
    cfg = merge(base, over)
    engine = cfg["association"]["merge_engine"]
    out = os.path.join(HERE, f"merge_debug_00824_{engine}.yaml")
    fb, fc = flat(base), flat(cfg)
    diff = {k: (fb.get(k), fc.get(k)) for k in sorted(set(fb) | set(fc)) if fb.get(k) != fc.get(k)}
    header = ("# GENERATED by make_merge_debug_config.py from lost3dsg/src/perception_module/config.yaml\n"
              "# (merge-algorithm lane, 2026-09-14). Do not edit; regenerate. A GRAPH_API_CONFIG file\n"
              "# REPLACES config.yaml, so everything not listed below is the tracked value verbatim.\n"
              "# KEYS THAT DIFFER FROM THE TRACKED config.yaml:\n")
    for k, (b, c) in diff.items():
        header += f"#   {k}: {b!r} -> {c!r}\n"
    with open(out, "w") as fh:
        fh.write(header)
        yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False, width=100)
    print(out)
    for k, (b, c) in diff.items():
        print(f"  {k}: {b!r} -> {c!r}")
    for key in ("association.merge_engine", "association.merge_ontology_channel",
                "association.merge_attribute_max_log_odds", "association.association_margin_m",
                "similarity.label", "similarity.color", "similarity.material", "similarity.description",
                "vlm.model", "vlm.enable_thinking"):
        print(f"  keep {key} = {fc.get(key)!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
